name: Tests

on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@master
            # Setup Python (faster than using Python container)
            - name: Setup Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.9"

            - name: Install pipenv
              run: |
                  python -m pip install --upgrade pipenv wheel
            - id: cache-pipenv
              uses: actions/cache@v1
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            - name: Install dependencies
              if: steps.cache-pipenv.outputs.cache-hit != 'true'
              run: |
                  pipenv install --deploy --dev

            - name: Run unit tests across multiple OS.
              run: |
                  pipenv run python test/unit_tests.py
