name: Tests

on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: Run unit tests across multiple OS.
              uses: actions/checkout@master
              with:
                  python-version: "3.9"
              run: |
                  pip install --user pipenv
                  pipenv install -d
                  pipenv run python test/unit_tests.py
