name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    # installation:
    #     runs-on: ${{ matrix.os }}
    #     strategy:
    #         matrix:
    #             os: [macos-latest, ubuntu-latest, windows-latest]
    #             python: ["3.9", "3.10"]

    #     steps:
    #         - uses: actions/checkout@master
    #         - uses: actions/setup-python@v2
    #           with:
    #               python-version: ${{ matrix.python }}

    #         - name: Test installation
    #           run: pip install "git+https://github.com/lewiswolf/drum-shape-predictor.git@dev#egg=kac_drumset"

    all-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                python: ["3.9", "3.10"]

        steps:
            - uses: actions/checkout@master
            - uses: lukka/get-cmake@latest 
            - uses: actions/setup-python@v2
              with:
                  python-version: ${{ matrix.python }}

            - name: Install pipenv
              run: python -m pip install --upgrade pipenv wheel
            - id: cache-pipenv
              uses: actions/cache@v1
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            - name: Install python dependencies
              # if: steps.cache-pipenv.outputs.cache-hit != 'true'
              run: pipenv install -d --python ${{ matrix.python }}

            - name: Build CPP
              run: pipenv run build

            - name: Lint project
              run: pipenv run flake8 --config=test/test.cfg

            - name: Assert types
              run: pipenv run mypy --config-file=test/test.cfg

            - name: Run unit tests
              run: pipenv run python test/test.py
