name: Tests

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    installation:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                python: ["3.9"]

        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python }}

            - name: Test installation
              run: pip install "git+https://github.com/lewiswolf/kac_drumset.git@dev#egg=kac_drumset"

    all-tests:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]
                python: ["3.9"] # torchaudio does not work on python 3.10

        steps:
            - uses: actions/checkout@master
              with:
                  submodules: recursive
            - uses: lukka/get-cmake@latest 
            - uses: actions/setup-python@v3
              with:
                  python-version: ${{ matrix.python }}

            - name: Install OS specific dependencies
              if: ${{ matrix.os == 'ubuntu-latest' }}
              run: sudo apt-get install libsndfile1

            - name: Install pipenv
              run: python -m pip install --upgrade pipenv wheel
            - id: cache-pipenv
              uses: actions/cache@v3
              with:
                  path: ~/.local/share/virtualenvs
                  key: ${{ runner.os }}-pipenv-${{ hashFiles('**/Pipfile.lock') }}

            - name: Install python dependencies
              run: pipenv install -d --python ${{ matrix.python }}

            - name: Build CPP
              run: pipenv run build

            - name: Lint project
              run: pipenv run flake8 --config=test/test.cfg

            - name: Assert types
              run: pipenv run mypy --config-file=test/test.cfg

            - name: Run unit tests
              run: pipenv run python test/test.py
