name: Tests

on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    test:
        # The type of runner that the job will run on
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: [macos-latest, ubuntu-latest, windows-latest]

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - uses: actions/checkout@master
            - uses: actions/setup-python@v2
              with:
                  python-version: "3.9"
            - name: Run unit tests across multiple OS.
              run: |
                  python -m pip install --upgrade pip
                  pip install --user pipenv
                  pipenv install -d
                  pipenv run python test/unit_tests.py
